###Recuperar las peliculas
GET http://localhost:3000/movies

###Recuperar una película por ID
GET http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08


###REcuperar todas la películas por un genero
GET http://localhost:3000/movies?genre=Action

### Crear una película con POST

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "rate": 9,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

###Actualizar una pelicula

PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 1998
}